### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by JackatDJL** [derjacklive/SongRaten#5]
- [ ] Presenter Code Für Buttons
- [ ] User Interface für Presenter Gamemode
- [ ] Player 1 wenn Programmiert dupblizieren und anpassen
- [ ] Webhook Testen
- [ ] In /game/index.html on fail auf /error.html
- [ ] Buzzer Codes
- [ ] Time and Date Webhook machen und Testen
<details><summary>Details</summary>
<p>

- [ ] Extra für Zukunft: Versch Gamemodes wie z.b. Presenter / Online / Matchmaking

</p>
</details>
